# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "thunderbolt" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8c1b870e-9ceb-407f-a1d8-b916765a47f0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0befe1bf-7eef-42eb-a17c-a7ea4c77e5dc" = {
    device = "/dev/disk/by-uuid/0befe1bf-7eef-42eb-a17c-a7ea4c77e5dc";
    allowDiscards = true;

    # Fix for an exploit: https://github.com/natanbc/nix-config/commit/ab94b87af329695b6684de1b39edaf7993866203
    # systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0+2+7+12+13+14+15:sha256=0000000000000000000000000000000000000000000000000000000000000000 --wipe-slot=tpm2 /dev/nvme0n1p2
    crypttabExtraOpts = [ "tpm2-device=auto" "tpm2-measure-pcr=yes" ];
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EDED-6AB2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/pool1" =
    { device = "pool1";
      fsType = "zfs";
    };

  sops.secrets."pool1.key" = {
    format = "binary";
    sopsFile = ./pool1.key;
    path = "/etc/pool1.key";
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp95s0.useDHCP = lib.mkDefault true;

  networking.hostId = "be9d47fd";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
