# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "thunderbolt" "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "vhci-hcd" "usbip_host" "usbip_core" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8b35486d-fd57-4fbc-9d08-b856646fe839";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9c0b5534-3f6e-47ff-b51c-4dda36f64199".device = "/dev/disk/by-uuid/9c0b5534-3f6e-47ff-b51c-4dda36f64199";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C272-8BCD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home/luana/ssd2" =
    { device = "/dev/disk/by-uuid/0a21e7ed-9bd4-48e7-92b6-ee0dfcc12086";
      fsType = "btrfs";
    };

 # swapDevices = [ {device = "/dev/nvme0n1p1";} ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp77s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp76s0.useDHCP = lib.mkDefault true;

  networking.hostId = "24af69ff";
  
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
