

;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #AAFFFFFF
background-alt = #AA373B41
foreground = #FF000000
primary = #FF000000
secondary = #FF000000 
alert = #FFFF5555
disabled = #FF000000




[bar/main]
width = 80%
offset-x = 10%
height = 22pt
radius = 15

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 2
padding-right = 2

module-margin = 1

separator = ""
separator-foreground = ${colors.disabled}

font-0 = monospace;2
font-1 = feather;2
font-2 = monospace bold;2

modules-left = launcher search
modules-center = date
modules-right = tray statusxfce settings powermenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

tray-position = none

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true





[bar/kdetop]
width = 3%
offset-x = 93%
offset-y = 0.3%
height = 15pt
radius = 10

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 1
padding-right = 1

module-margin = 1

separator = ""
separator-foreground = ${colors.disabled}

font-0 = monospace;2
font-1 = feather;2
font-2 = monospace bold;2

modules-left = 
; CPU/RAM/GPU/etc usage information (click to open, Rclick to close)
modules-center = status
modules-right = 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true





[bar/trickkde]

bottom = true
width = 1%
offset-x = 93%
; Enough to trick bottom KDE dock into not stop being floating when a window is maximised (why's this not an option in kde lmao?)
height = 36pt
border-size = 4pt
; ofc, I want it to be transparent, but it HAS to be transpqarent (or have a transparent border) to trick KDE
border-color = #00000000
radius = 15
foreground = #00FFFFFF
background = #00FFFFFF
modules-center = sep

[bar/trickkdetop]
width = 1%
offset-x = -93%
; Enough to trick top KDE panel into not stop being floating when a window is maximised (why's this not an option in kde lmao?)
height = 22pt
border-size = 4pt
; ofc, I want it to be transparent, but it HAS to be transpqarent (or have a transparent border) to trick KDE
border-color = #00000000 
radius = 15
foreground = #00FFFFFF
background = #00FFFFFF
modules-center = sep



[bar/status]

width = 27%
offset-y = 0.7%
height = 22pt
radius = 15
bottom = true


background = #00FFFFFF
foreground = #FFFFFFFF
primary = #FFFFFFFF
secondary = #FFFFFFFF
alert = #FFFFFFFF
disabled = #FFFFFFFF
background-alt = #FFFFFFFF


line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 1
padding-right = 2

module-margin = 1

separator = ""
separator-foreground = ${colors.disabled}

font-0 = monospace;2

modules-left =  memory cpu temperature gpu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true





[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>
click-right = pavucontrol
label-volume = %percentage%%

label-muted = 
label-muted-foreground = ${colors.disabled}


[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM: "
format-prefix-foreground = #FFFFFFFF
label = %percentage_used:2%%

[module/temperature]
type = internal/temperature
units = true
hwmon-path = /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon2/temp1_input
label = %temperature-c%
trep = %temperature-c%

[module/cpu]
type = internal/cpu
inherit = module/temperature
interval = 2
format-prefix = "CPU:"
format-prefix-foreground = #FFFFFFFF
label = %percentage:2%%

[module/date]
type = internal/date
interval = 1

date = %d/%m/%Y %H:%M:%S
date-alt = %A, %d/%m/%Y %H:%M:%S
; label-font = monospace bold;2
label = %{T2} %date% %{T-}
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = false

; vim:ft=dosini

;; Application Launcher Module

[module/launcher]
type = custom/text

content = 
; content-background = black
; content-foreground = green

click-left = ~/.config/rofi/launchers/type-3/launcher.sh
click-right = launcher_t7

;; Power Menu Module

[module/powermenu]
type = custom/text

content = 
; content-background = black
; content-foreground = red

; click-left = ~/.config/rofi/powermenu/type-4/powermenu.sh
click-left = xfce4-session-logout > ~/log-polybar-shutdown ;; for non-nixos: /usr/bin/xfce4-session-logout

[module/tray]
type = internal/tray

format-margin = 8px
tray-spacing = 8px

[module/whisker]
type = custom/text
content = W
click-left = xfce4-popup-whiskermenu

[module/settings]
type = custom/text
content = 
click-left = xfce4-settings-manager
click-right = ccsm

[module/search]
type = custom/text
content = 
click-left = ulauncher-toggle

[module/gpu]
type = custom/script
exec = echo $(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits)% $(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits)°C VRAM: $(nvidia-smi --query-gpu=utilization.memory --format=csv,noheader,nounits)%
label = GPU: %output%

[module/sep]
type = custom/text
format = 

[module/status]
type = custom/text
format = 
click-left = polybar status
click-right = bash ~/.restpolytop

[module/statusxfce]
type = custom/text
format = 
click-left = polybar status
click-right = bash ~/.restpolymain
